/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeColorRenderer */

#ifndef _Included_com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeColorRenderer
#define _Included_com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeColorRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeColorRenderer
 * Method:    surfaceCreated
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeColorRenderer_surfaceCreated
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeColorRenderer
 * Method:    surfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeColorRenderer_surfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeColorRenderer
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeColorRenderer_onDrawFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
