/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeSimpleRenderer */

#ifndef _Included_com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeSimpleRenderer
#define _Included_com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeSimpleRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeSimpleRenderer
 * Method:    surfaceCreated
 * Signature: (I)V
 */
JNIEXPORT void JNICALL
Java_com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeSimpleRenderer_surfaceCreated
        (JNIEnv *, jobject);

/*
 * Class:     com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeSimpleRenderer
 * Method:    surfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL
Java_com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeSimpleRenderer_surfaceChanged
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeSimpleRenderer
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_jeryzhang_opengl_opengl4androiddemo_ndk_NativeSimpleRenderer_onDrawFrame
        (JNIEnv *, jobject);

void JNICALL drawPoint();
void drawLine();
void drawTriancle();
#ifdef __cplusplus
}
#endif
#endif
